spring.application.name=boleia

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

spring.datasource.url=jdbc:postgresql://localhost:5412/boleia
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
server.port=8080
spring.datasource.driver-class-name=org.postgresql.Driver

# DataSource
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=update
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=update.sql
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-source=metadata
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.clean-disabled=true
spring.flyway.validate-on-migrate=true
spring.flyway.out-of-order=true
logging.level.org.flywaydb=DEBUG

# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true
logging.level.root=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

# Twilio credentials
twilio.accountSid=${TWILIO_ACCOUNT_SID}
twilio.authToken=${TWILIO_AUTH_TOKEN}
twilio.phoneNumber=${TWILIO_PHONE_NUMBER}

#senha do jwt
jwt.tokenKey="olhaaminhasenhadosloucoskkkvamosaissomostrartodasessassenhasmalucasparatodospoderemterumaboleiamagnifica"